services:
  - docker

before_install:
  - docker build -t phanumax/react-test -f ./client/Dockerfile.dev .

script:
  - docker run phanumax/react-test npm test -- --coverage

after_success:
  - docker build -t phanumax/muti-client ./client
  - docker build -t phanumax/multi-nginx ./nginx
  - docker build -t phanumax/multi-server ./server
  - docker build -t phanumax/multi-worker ./worker
  # Take images and push them to docker hub