language: generic

services:
  - docker

before_install:
  - docker build -t phanumax/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true phanumax/react-test npm test

after_success:
  - docker build -t phanumax/muti-client ./client
  - docker build -t phanumax/multi-nginx ./nginx
  - docker build -t phanumax/multi-server ./server
  - docker build -t phanumax/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push phanumax/multi-client
  - docker push phanumax/multi-nginx
  - docker push phanumax/multi-server
  - docker push phanumax/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-1-330415815932
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY